on:
  pull_request:
    # Don't try this, it doesnt work lol, it looks at the target branch to match regex
    # More info: https://github.com/orgs/community/discussions/26795#discussioncomment-3253430
    # branches-ignore:
    #   - "ignore/**"

name: Test branch ignore

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
      - id: skip
        run: |
          if [[ ${{ github.head_ref }} == *"ignore"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "skipping ${{ github.head_ref }}"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "not skipping ${{ github.head_ref }}"
          fi

  other-job:
    needs: [setup]
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.skip }} == 'false'
    steps:
      - name: run if not ignored
        run: |
          echo "hello world ${{ needs.setup.outputs.skip }}"
