on:
  pull_request:
    # Don't try this, it doesnt work lol, it looks at the target branch to match regex
    # More info: https://github.com/orgs/community/discussions/26795#discussioncomment-3253430
    # branches-ignore:
    #   - "ignore/**"

name: Test branch ignore

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ steps.condition.outputs.condition }}
    steps:
      - id: condition
        run: |
          if [[ ${{ github.head_ref }} == *"ignore"* ]]; then
            echo "condition=true" >> $GITHUB_OUTPUT
          else
            echo "condition=false" >> $GITHUB_OUTPUT  
          fi

  other-job:
    needs: [setup]
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.condition }} == 'true'
