name: blabla

on:
  push:

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check no quotes
      run: echo "no quotes"
      if: github.ref_name == ${{ github.event.repository.default_branch }}

    - name: Check quotes
      run: echo "no quotes"
      if: github.ref_name == '${{ github.event.repository.default_branch }}'
