name: pull request closed

on:
  pull_request:
    types: [closed]
  pull_request_target:
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Echo GITHUB_SHA
        run: |
          echo "${GITHUB_SHA}"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.base.sha }}"
