name: blabla
run-name: Release ${{ inputs.service || github.event.client_payload.service }} (${{ inputs.version || github.event.client_payload.version }}) to ${{ inputs.environment || github.event.client_payload.environment }}

on:
  repository_dispatch:
    types: [release]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - stage
        - prod
      service:
        description: 'Service to release'
        required: true
        type: choice
        options:
        - auth-api
        - auth-ui
        - feedback-portal
        - fim
        - ideas-api
        - public-api
      version:
        description: 'Service version to release'
        required: true
        type: string

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check no quotes
      run: echo "no quotes"
      if: github.ref_name == ${{ github.event.repository.default_branch }}

    - name: Check quotes
      run: echo "no quotes"
      if: github.ref_name == '${{ github.event.repository.default_branch }}'

    - name: Trigger Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repository: j6nca/github-actions-sandbox
        event-type: testing
        client-payload: '{"version": "blablabla"}'

    - name: Set env variables
      run: |
        echo "ENV=TEST_ENVIRONMENT" >> $GITHUB_ENV
        echo "SERVICE=TEST_SERVICE" >> $GITHUB_ENV
        echo "VERSION=TEST_VERSION" >> $GITHUB_ENV
