name: blabla
run-name: Release ${{ env.SERVICE }} (${{ env.VERSION }}) to ${{ env.ENV }}

on:
  push:

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check no quotes
      run: echo "no quotes"
      if: github.ref_name == ${{ github.event.repository.default_branch }}

    - name: Check quotes
      run: echo "no quotes"
      if: github.ref_name == '${{ github.event.repository.default_branch }}'

    - name: Trigger Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repository: j6nca/github-actions-sandbox
        event-type: testing
        client-payload: '{"version": "blablabla"}'

    - name: Set env variables
      run: |
        echo "ENV=TEST_ENVIRONMENT" >> $GITHUB_ENV
        echo "SERVICE=TEST_SERVICE" >> $GITHUB_ENV
        echo "VERSION=TEST_VERSION" >> $GITHUB_ENV
