# Sample release workflow
name: staggered
run-name: Staggered run \#${{ inputs.service }}

on:
  workflow_dispatch:
    inputs:
      num:
        description: 'arbitrary input'
        required: true
        type: string
        default: 'default'

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:

    - name: Get num running workflows and delay
      run: |
        NUM_RUNNING=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs\?status\=in_progress | jq '.total_count')
        # NUM_RUNNING=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs\?status\=in_progress | jq '.workflow_runs | length')
        echo "Number of currently running workflows: $NUM_RUNNING"
        echo "NUM_RUNNING=$NUM_RUNNING}" >> $GITHUB_ENV
        sleep $(( $NUM_RUNNING * 15 ))

    - name: Commit & push version changes
        id: commit-file
        shell: bash
        if: env.SKIP_COMMIT == 'false'
        run: |
          git pull --rebase --autostash
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          echo "input: '${{ inputs.num }}'" >> staggered.yaml
          git add staggered.yaml
          git commit -m "Staggered #${{ inputs.num }}"
          git push
    
    - name: ⛔ Send Slack Failure Notification
      if: failure()
      run: | 
          echo "Sending slack notification"
          SLACK_MESSAGE="There was an issue rolling out \`${{ env.SERVICE }}\` release \`${{ env.SHORT_SHA }}\`, please investigate"
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"${SLACK_MESSAGE}\"}" ${{ secrets.SLACK_WEBHOOK }}