name: Status Check 1
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        run: echo "done"


  status_check:
    needs:
      - run
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        run: echo "done"

