name: trufflehog scan

on:
  push:
    branches:
      - '**'
      - '!master'

permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write

jobs:
  call-workflow-passing-data:
    uses: j6nca/actions/.github/workflows/scan-trufflehog.yaml@main